# Generated by Django 5.1.2 on 2024-11-01 18:34

import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("pghistory", "0006_delete_aggregateevent"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Board",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[("p", "papers"), ("c", "code"), ("j", "jobs")],
                        default=None,
                        max_length=1,
                        null=True,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Keyword",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("c", "cosmology"),
                            ("p", "earth and planets"),
                            ("g", "galaxies"),
                            ("h", "high energy"),
                            ("t", "tech and methods"),
                            ("s", "sun and stars"),
                            ("m", "multimessenger"),
                        ],
                        default=None,
                        max_length=2,
                        null=True,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(max_length=10000)),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("edited", models.BooleanField(default=False)),
                ("nlikes", models.IntegerField(default=1)),
                (
                    "fans",
                    models.ManyToManyField(
                        editable=False,
                        related_name="liked_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="mb.comment",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                ("url", models.CharField(max_length=300)),
                ("date", models.DateTimeField()),
                ("edited", models.BooleanField(default=False)),
                ("nlikes", models.IntegerField(default=1)),
                ("score", models.FloatField(editable=False)),
                (
                    "board",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="posts",
                        to="mb.board",
                    ),
                ),
                (
                    "fans",
                    models.ManyToManyField(
                        editable=False,
                        related_name="liked_posts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "keywords",
                    models.ManyToManyField(
                        blank=True, related_name="posts", to="mb.keyword"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CommentHistory",
            fields=[
                ("pgh_id", models.AutoField(primary_key=True, serialize=False)),
                ("pgh_created_at", models.DateTimeField(auto_now_add=True)),
                ("pgh_label", models.TextField(help_text="The event label.")),
                ("id", models.BigIntegerField()),
                ("content", models.TextField(max_length=10000)),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("edited", models.BooleanField(default=False)),
                ("nlikes", models.IntegerField(default=1)),
                (
                    "parent",
                    models.ForeignKey(
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        related_query_name="+",
                        to="mb.comment",
                    ),
                ),
                (
                    "pgh_context",
                    models.ForeignKey(
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="pghistory.context",
                    ),
                ),
                (
                    "pgh_obj",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="events",
                        to="mb.comment",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        related_query_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        related_query_name="+",
                        to="mb.post",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="comment",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="mb.post",
            ),
        ),
        migrations.CreateModel(
            name="PostHistory",
            fields=[
                ("pgh_id", models.AutoField(primary_key=True, serialize=False)),
                ("pgh_created_at", models.DateTimeField(auto_now_add=True)),
                ("pgh_label", models.TextField(help_text="The event label.")),
                ("id", models.BigIntegerField()),
                ("title", models.CharField(max_length=120)),
                ("url", models.CharField(max_length=300)),
                ("date", models.DateTimeField()),
                ("edited", models.BooleanField(default=False)),
                ("nlikes", models.IntegerField(default=1)),
                ("score", models.FloatField(editable=False)),
                (
                    "board",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        related_query_name="+",
                        to="mb.board",
                    ),
                ),
                (
                    "pgh_context",
                    models.ForeignKey(
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="pghistory.context",
                    ),
                ),
                (
                    "pgh_obj",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="events",
                        to="mb.post",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        related_query_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="post",
            trigger=pgtrigger.compiler.Trigger(
                name="title_changed_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."title" IS DISTINCT FROM (NEW."title"))',
                    func='INSERT INTO "mb_posthistory" ("board_id", "date", "edited", "id", "nlikes", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "score", "title", "url", "user_id") VALUES (OLD."board_id", OLD."date", OLD."edited", OLD."id", OLD."nlikes", _pgh_attach_context(), NOW(), \'title_changed\', OLD."id", OLD."score", OLD."title", OLD."url", OLD."user_id"); RETURN NULL;',
                    hash="641cf1637d6b8166dec6d5d3353fa0a0e7270e2b",
                    operation="UPDATE",
                    pgid="pgtrigger_title_changed_update_c1830",
                    table="mb_post",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="comment",
            trigger=pgtrigger.compiler.Trigger(
                name="content_changed_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."content" IS DISTINCT FROM (NEW."content"))',
                    func='INSERT INTO "mb_commenthistory" ("content", "date", "edited", "id", "nlikes", "parent_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "post_id", "user_id") VALUES (OLD."content", OLD."date", OLD."edited", OLD."id", OLD."nlikes", OLD."parent_id", _pgh_attach_context(), NOW(), \'content_changed\', OLD."id", OLD."post_id", OLD."user_id"); RETURN NULL;',
                    hash="278d7d3c1231102b9e12b4d992f90d9352e5d053",
                    operation="UPDATE",
                    pgid="pgtrigger_content_changed_update_cdeb0",
                    table="mb_comment",
                    when="AFTER",
                ),
            ),
        ),
    ]
