# Generated by Django 5.1.2 on 2024-11-12 21:00

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mb", "0001_initial"),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name="post",
            name="title_changed_update",
        ),
        migrations.AddField(
            model_name="post",
            name="pinned",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="posthistory",
            name="pinned",
            field=models.BooleanField(default=False),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="post",
            trigger=pgtrigger.compiler.Trigger(
                name="title_changed_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."title" IS DISTINCT FROM (NEW."title"))',
                    func='INSERT INTO "mb_posthistory" ("board_id", "date", "edited", "id", "ncomments", "nlikes", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "pinned", "score", "title", "url", "user_id") VALUES (OLD."board_id", OLD."date", OLD."edited", OLD."id", OLD."ncomments", OLD."nlikes", _pgh_attach_context(), NOW(), \'title_changed\', OLD."id", OLD."pinned", OLD."score", OLD."title", OLD."url", OLD."user_id"); RETURN NULL;',
                    hash="aa971b39fb447ae64b1fa5c68766e1e74ed27629",
                    operation="UPDATE",
                    pgid="pgtrigger_title_changed_update_c1830",
                    table="mb_post",
                    when="AFTER",
                ),
            ),
        ),
    ]
