# Generated by Django 5.1.1 on 2024-09-25 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField()),
                ("title", models.CharField(max_length=120)),
                ("votes", models.IntegerField(default=1)),
                ("url", models.CharField(max_length=300)),
            ],
        ),
    ]
