# Generated by Django 5.1.2 on 2024-10-13 18:01

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="content",
            field=models.TextField(max_length=10000),
        ),
    ]
