# Generated by Django 5.1.2 on 2024-10-19 22:02

from django.db import migrations


def create_boards(apps, schema_editor):
    Board = apps.get_model('app', 'Board')
    boards = ["papers", "code", "jobs"]
    for name in boards:
        Board.objects.create(name=name)


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_boards),
    ]
