# Generated by Django 5.1.2 on 2024-10-19 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="board",
            field=models.CharField(
                choices=[("p", "papers"), ("j", "jobs"), ("c", "code")],
                max_length=1,
                null=True,
            ),
        ),
    ]
