# Generated by Django 5.1.2 on 2024-10-19 22:02
from django.db import migrations


def create_boards(apps, schema_editor):
    Board = apps.get_model("app", "Board")
    boards = ["papers", "code", "jobs"]
    for name in boards:
        Board.objects.create(name=name)


def create_keywords(apps, schema_editor):
    Keyword = apps.get_model("app", "Keyword")
    keywords = [
        "cosmology",
        "earth and planets",
        "galaxies",
        "high energy",
        "tech and methods",
        "sun and stars",
    ]
    for keyword in keywords:
        Keyword.objects.create(name=keyword)


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_boards),
        migrations.RunPython(create_keywords),
    ]
